apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bot-service-02-api
  namespace: sandbox
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bot-service-02-api
  minReplicas: 1
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
